INSERT INTO Cfg_DDD (`ESTADO`, `UF`, DDD, Regiao) VALUES
('Acre', 'AC','68', 'MTEROPOLITANA/INTERIOR'),
('Alagoas', 'AL', '82', 'METROPOLITANA'),
('Amazonas', 'AM', '97', 'INTERIOR'),
('Amazonas', 'AM', '92','METROPOLITANA'),
('Amapá', 'AP', '96','METROPOLITANA/INTERIOR'),
('Bahia', 'BA', '71','METROPOLITANA'),
('Bahia', 'BA', '74','INTERIOR'),
('Bahia', 'BA', '73','INTERIOR'),
('Bahia', 'BA', '75','INTERIOR'),
('Bahia', 'BA', '77','INTERIOR'),
('Ceará', 'CE', '85','METROPOLITANA'),
('Ceará', 'CE', '88','INTERIOR'),
('Distrito Federal', 'DF', '61','METROPOLITANA'),
('Paraíba', 'PB', '83','METROPOLITANA'),
( 'Rondônia', 'RO',  '69','METROPOLITANA'),
( 'Roraima', 'RR',  '95','METROPOLITANA'),
('Sergipe', 'SE', '79','METROPOLITANA'),
( 'Tocantins', 'TO', '63','METROPOLITANA'),
('Espírito Santo', 'ES', '27','METROPOLITANA'),
('Espírito Santo', 'ES', '28','INTERIOR'),
('Goiás', 'GO', '61','METROPOLITANA'),
('Goiás', 'GO', '64','INTERIOR'),
('Goiás', 'GO', '62','INTERIOR'),
('Maranhão', 'MA', '98','METORPOLITANA'),
('Maranhão', 'MA', '99','INTERIOR'),
('Minas Gerais', 'MG', '31','METROPOLITANA'),
('Minas Gerais', 'MG', '34','INTERIOR'),
('Minas Gerais', 'MG', '37','INTERIOR'),
('Minas Gerais', 'MG', '33','INTERIOR'),
('Minas Gerais', 'MG', '35','INTERIOR'),
('Minas Gerais', 'MG', '38','INTERIOR'),
('Minas Gerais', 'MG', '32','INTERIOR'),
('Mato Grosso do Sul', 'MS', '67','METROPOLITANA/INTERIOR'),
('Mato Grosso', 'MT',  '65','METROPOLITANA'),
('Mato Grosso', 'MT',  '66','INTERIOR'),
('Pará', 'PA', '91','METROPOLITANA'),
('Pará', 'PA', '94','INTERIOR'),
('Pará', 'PA', '93','INTERIOR'),
('Pernambuco', 'PE',  '81','METROPOLITANA'),
('Pernambuco', 'PE',  '87','INTERIOR'),
('Piauí', 'PI',  '89','METROPOLITANA'),
('Piauí', 'PI',  '86','INTERIOR'),
('Paraná', 'PR', '43','INTERIOR'),
('Paraná', 'PR', '41','METROPOLITANA'),
('Paraná', 'PR', '42','INTERIOR'),
('Paraná', 'PR', '44','INTERIOR'),
('Paraná', 'PR', '45','INTERIOR'),
('Paraná', 'PR', '46','INTERIOR'),
('Rio de Janeiro', 'RJ', '24','INTERIOR'),
('Rio de Janeiro', 'RJ', '22', 'INTERIOR'),
('Rio de Janeiro', 'RJ', '21','METROPOLITANA'),
('Rio Grande do Norte', 'RN',  '84', 'METROPOLITANA'),
('Rio Grande do Sul', 'RS', '53','INTERIOR'),
('Rio Grande do Sul', 'RS', '54','INTERIOR'),
('Rio Grande do Sul', 'RS', '55','INTERIOR'),
('Rio Grande do Sul', 'RS', '51','METROPOLITANA'),
('Santa Catarina', 'SC', '47','METROPOLITANA'),
('Santa Catarina', 'SC', '48','INTERIOR'),
('Santa Catarina', 'SC', '49','INTERIOR'),
('São Paulo', 'SP', '11','METROPOLITANA'),
('São Paulo', 'SP', '12','INTERIOR'),
('São Paulo', 'SP', '13','INTERIOR'),
('São Paulo', 'SP', '14','INTERIOR'),
('São Paulo', 'SP', '15','INTERIOR'),
('São Paulo', 'SP', '16','INTERIOR'),
('São Paulo', 'SP', '17','INTERIOR'),
('São Paulo', 'SP', '18','INTERIOR'),
('São Paulo', 'SP', '19','INTERIOR');